# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cria\xe7\xe3o')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de Atualiza\xe7\xe3o')),
                ('url', models.URLField(db_index=True, verbose_name='URL')),
                ('code', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='C\xf3digo')),
            ],
            options={
                'verbose_name': 'URL Encurtada',
                'verbose_name_plural': 'URLs Encurtadas',
            },
        ),
    ]
